defmodule BattleshipWeb.GameLive.PlayComponent do
  use BattleshipWeb, :live_component

  alias Battleship.Gameboard

  @impl true
  def mount(socket) do
    # This new gameboard will be replaced with gameboard generated by another player or computer
    {:ok, socket |> assign(:enemy_gameboard, Gameboard.generate_board())}
  end

  @impl true
  def handle_event("click", %{"row" => row, "col" => col}, socket) do
    %{board: new_enemy_board, hit?: _hit?} =
      Gameboard.attack(socket.assigns.enemy_gameboard, [
        String.to_integer(row),
        String.to_integer(col)
      ])

    {:noreply, socket |> assign(:enemy_gameboard, new_enemy_board)}
  end
end
